### ISSUE TITLE
[BUG] /authme unregister playernickname caused error

### ISSUE THREAD

**Issue by F3F5** [UnDeadlyDev/UTitleAuth#1]
![image](https://user-images.githubusercontent.com/108226177/224692552-19e2d2ed-87e6-4d72-9755-ab609260b9ba.png)

this is after unregister only

**Comment by F3F5** [comment]
@UnDeadlyDev error causing only with console (without playing in server) offline unregister

**Comment by UnDeadlyDev** [comment]
Ooooh you don't mention nothing of this al right now understans sorry

**Comment by F3F5** [comment]
reopen ticked pls

**Comment by UnDeadlyDev** [comment]
Problem fixed
