### ISSUE TITLE
Error in receiving authorization status.

### ISSUE THREAD

**Issue by Regomy** [UnDeadlyDev/UTitleAuth#2]
The problem is that by using playerjoinevent and checking isAuthorizated, you get its primary value false. Oddly enough, then it immediately calls playerloginevent, but what's the problem? And the problem is that the authorization tiles appear for seconds, which is the problem.

**Comment by UnDeadlyDev** [comment]
What do you recommend me

**Comment by Regomy** [comment]
> What do you recommend me

If I knew, for myself I took such a fix, but maybe you can come up with something better, I use the sheller with a delay of 20 ticks on entry, and in this sheller I execute code, during this time AuthMe has time to check the player, and no problems.

**Comment by UnDeadlyDev** [comment]
> > What do you recommend me
> 
> If I knew, for myself I took such a fix, but maybe you can come up with something better, I use the scheduller with a delay of 20 ticks on entry, and in this scheduller I execute code, during this time AuthMe has time to check the player, and no problems.

Am not sure of what is exactly but update ando fix others

**Comment by Regomy** [comment]
> > > What do you recommend me
> > 
> > 
> > If I knew, for myself I took such a fix, but maybe you can come up with something better, I use the scheduller with a delay of 20 ticks on entry, and in this scheduller I execute code, during this time AuthMe has time to check the player, and no problems.
> 
> Am not sure of what is exactly but update ando fix others

I installed the latest version, in general, now even after authorization, or if I am already authorized and logged into the session appears a message and a title that says authorize.

**Comment by UnDeadlyDev** [comment]
Solved?

**Comment by Regomy** [comment]
> Solved?

The problem is still there, please watch the video: https://youtu.be/YXv_EawElf4

**Comment by UnDeadlyDev** [comment]
ooh is for you have set true "sessions" of authme and bungeecord hook my plugin send correctly title and authme send so fast to the player to lobby and dont have time for send login title

**Comment by Regomy** [comment]
I don't understand anything, I don't know English, and the translator killed your text to a simple conjunction "my plugin does something, and authme does something not."

~ From what I've read, I suggest to use scheduler after all
`        Bukkit.getScheduler().scheduleSyncDelayedTask(AuthMeApi.getInstance().getPlugin(), () -> {

            if(!AuthMeApi.getInstance().isRegistered(name)) {
                      //code if player not register here
            } else if(!AuthMeApi.getInstance().isAuthenticated(player)) {
                     // code if player not login here
            }

        },20);`

**Comment by UnDeadlyDev** [comment]
OOOOH AAHAHA am now understand this and have solution without delay

**Comment by UnDeadlyDev** [comment]
test this version for check 
[7.8.0 TEST.zip](https://github.com/UnDeadlyDev/UTitleAuth/files/11267764/7.8.0.TEST.zip)

**Comment by UnDeadlyDev** [comment]
On set delay title is not send on change server first need set delay on teleport

**Comment by Regomy** [comment]
> On set delay title is not send on change server first need set delay on teleport

Installed with the config from 7.7.0 still left the problem.

**Comment by Regomy** [comment]
I set the values to:
      time: #This is a times of title in ticks.
        fadein: 40
        stay: 100
        fadeout: 40
    login:
      time: #This is a times of title in ticks.
        fadein: 40
        stay: 100
        fadeout: 40
nothing has changed.

**Comment by Regomy** [comment]
> On change player server so fast on login UTitleAuth don't show a title is for change server not my plugin

I don't understand anything, what you write I just don't understand, please rephrase it, I really don't understand what the translator gives me.

- I created a pull request
