### ISSUE TITLE
Error displaying actionbar messages

### ISSUE THREAD

**Issue by iwdath** [UnDeadlyDev/UTitleAuth#9]
If you use the settings `forceKickAfterRegister: false` and `forceLoginAfterRegister: true` in the AuthMe plugin, actionbar messages will overlap each other.

Video: https://youtu.be/861JSIfidF8

**Comment by UnDeadlyDev** [comment]
Please check last version

**Comment by iwdath** [comment]
All is working now. Thanks for the quick fix.

**Comment by iwdath** [comment]
Today, the problem reappeared, exactly the same as before. I enabled the AuthMe setting `enablePermissionCheck: true` and thought that was the cause, but after disabling it, the display issue remained. I also tried reinstalling the UTitleAuth plugin, but that didn’t help.

**Comment by UnDeadlyDev** [comment]
Look version 7.9.9

**Comment by iwdath** [comment]
It seems to be working. I'll let you know if there are any more issues.
